### ISSUE TITLE
CareGap determination should just use the calculated score

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cqf-ruler#203]
CareGap determination is recalculating the score from the MeasureReport, it should just use the MeasureReport score:
https://github.com/DBCG/cqf-ruler/blob/master/r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java#L265

**Comment by Capt-Mac** [comment]
fixed in migration to clinical-reasoning
