### ISSUE TITLE
CMS105 FHIR401 submit data causing Null pointer exception

### ISSUE THREAD

**Issue by karthikishorejs** [cqframework/cqf-ruler#206]
**Measure** - CMS105 FHIR 401
**Input:** 
localhost:8080/cqf-ruler-r4/fhir/Measure/measure-EXM105-9.1.000/$submit-data
**Expected Result**
Response 201 created
**Actual Result** Null pointer exception

**Comment by Capt-Mac** [comment]
this operation migrated to clinical-reasoning project, please provide data and submit new issue if still a problem https://github.com/cqframework/clinical-reasoning
