### ISSUE TITLE
Null pointer exception on currentContext For the applicability condition in R4HookEvaluator

### ISSUE THREAD

**Issue by davidouagne** [cqframework/cqf-ruler#280]
Hi,

As expressed in the title. A null pointer exception is raised when in the applicability condition there is a need to do a retrieve (the current context is null).

To work around the problem, I modified CdsHooksServlet:

R4HookEvaluator evaluator = new R4HookEvaluator();

// this line has been added
context.enterContext("Patient");
EvaluationContext<PlanDefinition> evaluationContext = new R4EvaluationContext(hook, version,
                    FhirContext.forR4().newRestfulGenericClient(baseUrl), jpaTerminologyProvider, context, library,
                    planDefinition, this.getProviderConfiguration());

String jsonResponse = toJsonResponse(evaluator.evaluate(evaluationContext));
// this line has been added
context.exitContext();

But I'm not sure it's a solid solution, I even think the opposite.

Regards

**Comment by barhodes** [comment]
The code this bug was in no longer exists.
