### ISSUE TITLE
Refactor CDS Hooks plugin to use PlanDefinitionProcessor

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cqf-ruler#539]
Right now the CDS Hooks plugin uses a different PlanDefinition processor. This is because there is use-case specific logic that supports a dynamicValue with a path of "action.extension" to be interpreted as the value for the "indicator".

Add this behavior as backwards-compatible, but deprecated, functionality to the standard PlanDefinition processor.

Then refactor the CDS Hooks plugin to use the standard PlanDefinition processor.

Issue a warning to the log whenever this deprecated capability is used, and point the warning to a page in the wiki that demonstrates how to update content that uses it to use a standards-compliant approach (which is to have the dynamicValue set the priority, and have the priority map to the indicator in the CDS Hooks card transform.

**Comment by JPercival** [comment]
Blocked by needing some changes in the API for the PlanDefinition processor. It currently doesn't support using a JPA service correctly.

**Comment by JPercival** [comment]
Whoops. Wrong ticket.

**Comment by NataliaSmileDigital** [comment]
@barhodes can you please confirm if this is resolved? Thank you

**Comment by barhodes** [comment]
The CDS Hooks plugin in the JPA Server Starter is using the PlanDefinitionProcessor, yes.
