### ISSUE TITLE
error compiling latest at Use evaluator utilities (#666)

### ISSUE THREAD

**Issue by javaswinger** [cqframework/cqf-ruler#668]
[INFO] cqf-ruler-cql 0.9.0-SNAPSHOT ....................... FAILURE [ 16.429 s]
[INFO] cqf-ruler-cr 0.9.0-SNAPSHOT ........................ SKIPPED
[INFO] cqf-ruler-dev-tools 0.9.0-SNAPSHOT ................. SKIPPED
[INFO] cqf-ruler-security 0.9.0-SNAPSHOT .................. SKIPPED
[INFO] cqf-ruler-cpg 0.9.0-SNAPSHOT ....................... SKIPPED
[INFO] cqf-ruler-cds-hooks 0.9.0-SNAPSHOT ................. SKIPPED
[INFO] cqf-ruler-case-reporting 0.9.0-SNAPSHOT ............ SKIPPED
[INFO] cqf-ruler-ra 0.9.0-SNAPSHOT ........................ SKIPPED
[INFO] cqf-ruler-sdc 0.9.0-SNAPSHOT ....................... SKIPPED
[INFO] cqf-ruler-server 0.9.0-SNAPSHOT .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:35 min
[INFO] Finished at: 2022-11-23T13:40:10-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cqf-ruler-cql: Compilation failure
[ERROR] /C:/Users/revans/Documents/Git/cqf-ruler/plugin/cql/src/main/java/org/opencds/cqf/ruler/cql/CqlConfig.java:[208,41] constructor TranslatingLibraryLoader in class org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader cannot be applied to given types;
[ERROR]   required: org.cqframework.cql.cql2elm.ModelManager,java.util.List<org.cqframework.cql.cql2elm.LibrarySourceProvider>,org.cqframework.cql.cql2elm.CqlTranslatorOptions,org.hl7.cql.model.NamespaceInfo
[ERROR]   found:    org.cqframework.cql.cql2elm.ModelManager,java.util.List<org.cqframework.cql.cql2elm.LibrarySourceProvider>,org.cqframework.cql.cql2elm.CqlTranslatorOptions
[ERROR]   reason: actual and formal argument lists differ in length

**Comment by rob-reynolds** [comment]
Please try latest.  It should be compiling now.

**Comment by javaswinger** [comment]
Thank you Rob as I built it today
